services:
  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - CLICKHOUSE_URL=http://clickhouse:8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DATABASE=default
    depends_on:
      - redis
      - clickhouse

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  
  clickhouse:
    build:
      context: ./clickhouse
      dockerfile: Dockerfile
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
    environment: 
      - CLICKHOUSE_PASSWORD=default

  preview:
    build:
      context: ./preview
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - 3000:3000
    depends_on:
      - redis

volumes:
  redis-data:
  clickhouse-data:
  clickhouse-logs:

