app = "listen-redis"
primary_region = "waw"

[build]
dockerfile = "Dockerfile"

[mounts]
source = "redis_data"
destination = "/data"

[[services]]
internal_port = 6379
protocol = "tcp"

[[services.ports]]
port = 6379
